export const types = Object.freeze({
    dialogs: {
        SEND_MESSAGE: 'DIALOGS/SEND_MESSAGE'
    },
    users: {
        FOLLOW: 'USERS/FOLLOW',
        UNFOLLOW: 'USERS/UNFOLLOW',
        SET_USERS: 'USERS/SET_USERS',
        SET_CURRENT_PAGE: 'USERS/SET_CURRENT_PAGE',
        SET_LOADING: 'USERS/SET_LOADING',
        SET_FOLLOW_PENDING: 'USERS/SET_FOLLOW_PENDING'
    },
    profile: {
        ADD_POST: 'PROFILE/ADD_POST',
        SET_USER_PROFILE: 'PROFILE/SET_USER_PROFILE',
        SET_USER_STATUS: 'PROFILE/SET_USER_STATUS',
        UPDATE_USER_STATUS: 'PROFILE/UPDATE_USER_STATUS',
        SET_USER_IS_LOADING: 'PROFILE/SET_USER_IS_LOADING'
    },
    auth: {
        SET_USER_DATA: 'AUTH/SET_USER_DATA',
        SET_IS_LOADING: 'AUTH/SET_IS_LOADING',
        LOGIN: 'AUTH/LOGIN',
        LOGOUT: 'AUTH/LOGOUT'
    }
})